version: '3.8'

services:
  web:
    build: .
    entrypoint: ["gunicorn", "-b", "0.0.0.0:5000", "-w", "4", "src:create_app()"]
    env_file:
      - .env
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./src:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always
