name: Flask Continuous Integration

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - run: flake8 src tests
      - run: pylint src tests
      - run: black --check src tests
      - run: isort --check src tests

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - run: coverage run -m pytest -v tests
      - run: coverage report

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - run: docker image build -t flask_demo_login .
